---
# Network setup

- name: Disable ipv6
  blockinfile:
    path: /etc/sysctl.conf
    block:
      net.ipv6.conf.all.disable_ipv6 = 1

      net.ipv6.conf.default.disable_ipv6 = 1
  notify: restart network

- name: set timezone
  timezone:
    name: Europe/Kiev

