---
# Install Docker-CE

- name: Uninstall old versions if exists
  yum: name={{ item }} state=absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine


- name: Install required packages
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: yum update
  action: yum name=* state=latest

- name: Install Docker CE
  yum: name={{ item }} state=present
  with_items:
    - docker-ce

- name: Restart service docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Init a new swarm with default parameters
  shell: docker swarm init


